# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:
  basic-cluster-props: &basic-cluster-props
    spark_version: "11.1.x-cpu-ml-scala2.12"

  basic-static-cluster: &basic-static-cluster
    <<: *basic-cluster-props
    instance_pool_name: "f8s-v2-pool"
    driver_instance_pool_name: "f8s-v2-pool"

  builder-cluster: &builder-cluster
    new_cluster:
      num_workers: 6
      <<: *basic-static-cluster

  loader-cluster: &loader-cluster
    new_cluster:
      num_workers: 1
      <<: *basic-static-cluster

  loader-task: &loader-task
    job_cluster_key: "loader-cluster"
    python_wheel_task:
      package_name: "e2e_mlops_demo"
      entry_point: "loader"
      parameters: [ "--conf-file", "file:fuse://conf/tasks/loader.yml" ]

  builder-task: &builder-task
    job_cluster_key: "builder-cluster"
    python_wheel_task:
      package_name: "e2e_mlops_demo"
      entry_point: "builder"
      parameters: [ "--conf-file", "file:fuse://conf/tasks/builder.yml" ]

environments:
  default:
    jobs:
      - name: "e2e-mlops-demo-main"
        job_clusters:
          - job_cluster_key: "loader-cluster"
            <<: *loader-cluster
          - job_cluster_key: "builder-cluster"
            <<: *builder-cluster
        tasks:
          - task_key: "loader"
            <<: *loader-task
          - task_key: "builder"
            <<: *builder-task
            depends_on:
              - task_key: "loader"

      - name: "e2e-mlops-demo-loader"
        job_clusters:
          - job_cluster_key: "loader-cluster"
            <<: *loader-cluster
        tasks:
          - task_key: "loader"
            <<: *loader-task
      - name: "e2e-mlops-demo-builder"
        job_clusters:
          - job_cluster_key: "builder-cluster"
            <<: *builder-cluster
        tasks:
          - task_key: "builder"
            <<: *builder-task