FROM python:3.9.13

WORKDIR /mlflow

RUN --mount=type=cache,target=/root/.cache pip install mlflow==1.27.0

ENV BACKEND_URI sqlite:////mlflow/mlflow.db
ENV ARTIFACT_ROOT /mlflow/artifacts

CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} --host 0.0.0.0 --port 5005