FROM python:3.9.13

COPY --from=openjdk:11-jre-slim /usr/local/openjdk-11 /usr/local/openjdk
ENV JAVA_HOME /usr/local/openjdk
RUN update-alternatives --install /usr/bin/java java /usr/local/openjdk/bin/java 1

WORKDIR /code

COPY . .

RUN --mount=type=cache,target=/root/.cache pip install -e ".[dev]"


