version: '3'
services:
  kafka:
    image: "confluentinc/cp-kafka"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - '9092:9092'
    command: >
      sh -c "echo "clientPort=2181" > zookeeper.properties
             echo 'dataDir=/var/lib/zookeeper/data' >> zookeeper.properties
             echo 'dataLogDir=/var/lib/zookeeper/log' >> zookeeper.properties
             zookeeper-server-start zookeeper.properties &
             echo '' > /etc/confluent/docker/ensure
             /etc/confluent/docker/run"

  mlflow:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.mlflow
    ports:
      - '5005:5005'